ALTER USER "SA" SET PASSWORD 'jakarta';

CREATE USER "SALES" PASSWORD 'jakarta';

CREATE ROLE "SALES_ROLE";

GRANT "SALES_ROLE" TO SALES ;

GRANT SELECT, UPDATE, INSERT ON TABLE SALES.CUSTOMER TO SALES_ROLE;
GRANT SELECT, UPDATE, INSERT ON TABLE SALES.PRODUCT TO SALES_ROLE;
GRANT SELECT, UPDATE, INSERT ON TABLE SALES.INVOICE TO SALES_ROLE;
GRANT SELECT, UPDATE, INSERT ON TABLE SALES.ITEM TO SALES_ROLE;